fixed

diff --git a/files/hooks/entrypoint-pre.d/20_minecraftforge b/files/hooks/entrypoint-pre.d/20_minecraftforge
--- a/files/hooks/entrypoint-pre.d/20_minecraftforge
+++ b/files/hooks/entrypoint-pre.d/20_minecraftforge
@@ -36,16 +36,20 @@ fi
 [ ! -f "${MC_HOME}/server/start.sh" ] && cp /opt/default_start.sh ${MC_HOME}/server/start.sh
 chmod +x ${MC_HOME}/server/start.sh
 
-[ "${DATA_DIR_EMPTY}" == "0" ] && exit 0
+#[ "${DATA_DIR_EMPTY}" == "0" ] && exit 0
 
-echo "Downloading Forge Installer ${FORGE_URL}"
-curl -o /tmp/${FORGE_INSTALLER_JAR} ${FORGE_URL}
-[ "$?" != "0" ] && die "curl command failed"
-cd ${MC_HOME}/server && java -jar /tmp/${FORGE_INSTALLER_JAR} --installServer
-[ "$?" != "0" ] && die "Forge java installer failed"
-rm -f /tmp/${FORGE_INSTALLER_JAR}
+if [ ! -f "${MC_HOME}/server/forge-${MINECRAFT_VERSION}-${FORGE_VERSION}-${MINECRAFT_VERSION}-universal.jar" ]; then
+  echo "Downloading Forge Installer ${FORGE_URL}"
+  curl -o /tmp/${FORGE_INSTALLER_JAR} ${FORGE_URL}
+  [ "$?" != "0" ] && die "curl command failed"
+  cd ${MC_HOME}/server && java -jar /tmp/${FORGE_INSTALLER_JAR} --installServer
+  [ "$?" != "0" ] && die "Forge java installer failed"
+  rm -f /tmp/${FORGE_INSTALLER_JAR}
+fi
 
 [ ! -f ${MC_HOME}/server/eula.txt ] && touch ${MC_HOME}/server/eula.txt
 [ "$(grep 'eula=true' ${MC_HOME}/server/eula.txt)" == "" ] && cat <<'EOF' > ${MC_HOME}/server/eula.txt
 eula=true
 EOF
+
+echo "Finished hook"
